import { useCallback, useMemo } from 'react'

const useSalaryClaimsViewModels = (args) => {
  const {
    selectedClaimKeys,
    setSelectedClaimKeys,
    selectedClaim,
    selectedClaimTypeMeta,
    statusColorMap,
    submittedClaimItems,
    selectedClaimItem,
    isItemDetailsVisible,
    selectedClaimItemDetails,
    submittedTotalLabel,
    submittedDisplayTotal,
    claimHistoryEntries,
    claimWorkflowState,
    selectedClaimActions,
    truncateAttachmentLabel,
    formatDate,
    formatDateTime,
    formatCurrency,
    backToClaimsPage,
    selectClaimItem,
    closeItemDetails,
    openAttachmentPreview,
    triggerClaimAction,
    renderItemDetailsField,
    search,
    period,
    sort,
    typeFilter,
    statusFilter,
    claimSortOptions,
    claimTypeOptions,
    claimStatusOptions,
    filteredClaimRows,
    groupedVisibleClaimRows,
    rowsToShow,
    claimRowsCount,
    isClaimsLoading,
    toTypeLabel,
    setSearch,
    setPeriod,
    setSort,
    setTypeFilter,
    setStatusFilter,
    clearClaimFilters,
    openBulkActionModal,
    openBulkPaymentModal,
    canBulkActOnClaim,
    canBulkActOnSalaryClaim,
    getClaimKey,
    toggleClaimGroupSelection,
    toggleSalaryGroupSelection,
    openClaimDetail,
    buildClaimRowActionItems,
    setRowsToShow,
    salarySearch,
    salaryPeriod,
    salarySort,
    salaryStatusFilter,
    salarySortOptions,
    salaryStatusOptions,
    filteredSalaryRows,
    groupedVisibleSalaryRows,
    salaryRowsToShow,
    salaryTotalCount,
    parseAmount,
    getSalaryAdjustmentsTotal,
    getSalaryProjectedNet,
    setSalarySearch,
    setSalaryPeriod,
    setSalarySort,
    setSalaryStatusFilter,
    clearSalaryFilters,
    setSalaryRowsToShow,
    overtimeSearch,
    overtimePeriod,
    overtimeSort,
    overtimeStatusFilter,
    overtimeStatusOptions,
    overtimeSortOptions,
    filteredOvertimeRows,
    visibleOvertimeRows,
    groupedVisibleOvertimeRows,
    overtimeRowsToShow,
    overtimeTotalCount,
    getStatusBadge,
    getOvertimeWorkflowStatusLabel,
    getOvertimeWorkflowPendingActionHint,
    getDisplayOvertimeId,
    getOvertimeStartDateTimeLabel,
    getOvertimeEndDateTimeLabel,
    formatOvertimeDate,
    getOvertimeReviewActionConfig,
    setOvertimeSearch,
    setOvertimePeriod,
    setOvertimeSort,
    setOvertimeStatusFilter,
    clearOvertimeFilters,
    setOvertimeRowsToShow,
    approveOvertime,
    rejectOvertime,
    openOvertimeDetail,
    assignmentSearch,
    assignmentSort,
    assignmentSortOptions,
    assignmentTeamFilter,
    assignmentTeamOptions,
    filteredAssignmentRows,
    groupedVisibleAssignmentRows,
    assignmentRowsToShow,
    assignmentHistory,
    isAssignmentsLoading,
    assignmentLoadError,
    assignmentTotalCount,
    formatMonth,
    getAssignmentNetAssigned,
    setAssignmentSearch,
    setAssignmentSort,
    setAssignmentTeamFilter,
    clearAssignmentFilters,
    openCreateAssignment,
    openEditAssignment,
    openAssignmentDetail,
    resumeAssignmentDraft,
    deleteAssignmentRow,
    setAssignmentRowsToShow,
    retryLoadAssignments,
    otRateSettings,
    otRateDirty,
    updateOvertimeRateField,
    updateOvertimeBaseHourField,
    updateOvertimeApplicabilityField,
    updateOvertimeRoleOverrideField,
    resetOvertimeRates,
    reloadOvertimeRates,
    persistOvertimeRates,
  } = args

  const isClaimKeySelected = useCallback((key) => selectedClaimKeys.has(key), [selectedClaimKeys])

  const clearSelection = useCallback(() => setSelectedClaimKeys(new Set()), [setSelectedClaimKeys])

  const claimDetailVm = useMemo(
    () => ({
      selectedClaim,
      selectedClaimTypeMeta,
      statusColorMap,
      submittedClaimItems,
      selectedClaimItem,
      isItemDetailsVisible,
      selectedClaimItemDetails,
      submittedTotalLabel,
      submittedDisplayTotal,
      claimHistoryEntries,
      claimWorkflowState,
      selectedClaimActions,
      truncateAttachmentLabel,
      formatDate,
      formatDateTime,
      formatCurrency,
    }),
    [
      selectedClaim,
      selectedClaimTypeMeta,
      statusColorMap,
      submittedClaimItems,
      selectedClaimItem,
      isItemDetailsVisible,
      selectedClaimItemDetails,
      submittedTotalLabel,
      submittedDisplayTotal,
      claimHistoryEntries,
      claimWorkflowState,
      selectedClaimActions,
      truncateAttachmentLabel,
      formatDate,
      formatDateTime,
      formatCurrency,
    ],
  )

  const claimDetailHandlers = useMemo(
    () => ({
      onBack: backToClaimsPage,
      onSelectClaimItem: selectClaimItem,
      onCloseItemDetails: closeItemDetails,
      onOpenAttachmentPreview: openAttachmentPreview,
      onTriggerClaimAction: triggerClaimAction,
      renderItemDetailsField,
    }),
    [
      backToClaimsPage,
      selectClaimItem,
      closeItemDetails,
      openAttachmentPreview,
      triggerClaimAction,
      renderItemDetailsField,
    ],
  )

  const claimRecordsVm = useMemo(
    () => ({
      search,
      period,
      sort,
      typeFilter,
      statusFilter,
      claimSortOptions,
      claimTypeOptions,
      claimStatusOptions,
      filteredClaimRows,
      groupedVisibleClaimRows,
      selectedClaimKeys,
      rowsToShow,
      totalCount: claimRowsCount,
      isLoading: isClaimsLoading,
      formatCurrency,
      formatDate,
      toTypeLabel,
      statusColorMap,
    }),
    [
      search,
      period,
      sort,
      typeFilter,
      statusFilter,
      claimSortOptions,
      claimTypeOptions,
      claimStatusOptions,
      filteredClaimRows,
      groupedVisibleClaimRows,
      selectedClaimKeys,
      rowsToShow,
      claimRowsCount,
      isClaimsLoading,
      formatCurrency,
      formatDate,
      toTypeLabel,
      statusColorMap,
    ],
  )

  const claimRecordsHandlers = useMemo(
    () => ({
      setSearch,
      setPeriod,
      setSort,
      setTypeFilter,
      setStatusFilter,
      clearClaimFilters,
      clearSelection,
      openBulkActionModal,
      canBulkActOnClaim,
      getClaimKey,
      isClaimKeySelected,
      toggleClaimGroupSelection,
      openClaimDetail,
      buildClaimRowActionItems,
      setRowsToShow,
    }),
    [
      setSearch,
      setPeriod,
      setSort,
      setTypeFilter,
      setStatusFilter,
      clearClaimFilters,
      clearSelection,
      openBulkActionModal,
      canBulkActOnClaim,
      getClaimKey,
      isClaimKeySelected,
      toggleClaimGroupSelection,
      openClaimDetail,
      buildClaimRowActionItems,
      setRowsToShow,
    ],
  )

  const salaryRecordsVm = useMemo(
    () => ({
      salarySearch,
      salaryPeriod,
      salarySort,
      salaryStatusFilter,
      salarySortOptions,
      salaryStatusOptions,
      filteredSalaryRows,
      groupedVisibleSalaryRows,
      selectedClaimKeys,
      salaryRowsToShow,
      totalCount: salaryTotalCount,
      isLoading: isClaimsLoading,
      formatCurrency,
      formatDate,
      parseAmount,
      getSalaryAdjustmentsTotal,
      getSalaryProjectedNet,
      statusColorMap,
    }),
    [
      salarySearch,
      salaryPeriod,
      salarySort,
      salaryStatusFilter,
      salarySortOptions,
      salaryStatusOptions,
      filteredSalaryRows,
      groupedVisibleSalaryRows,
      selectedClaimKeys,
      salaryRowsToShow,
      salaryTotalCount,
      isClaimsLoading,
      formatCurrency,
      formatDate,
      parseAmount,
      getSalaryAdjustmentsTotal,
      getSalaryProjectedNet,
      statusColorMap,
    ],
  )

  const salaryRecordsHandlers = useMemo(
    () => ({
      setSalarySearch,
      setSalaryPeriod,
      setSalarySort,
      setSalaryStatusFilter,
      clearSalaryFilters,
      clearSelection,
      openBulkActionModal,
      openBulkPaymentModal,
      canBulkActOnSalaryClaim,
      getClaimKey,
      isClaimKeySelected,
      toggleSalaryGroupSelection,
      openClaimDetail,
      buildClaimRowActionItems,
      setSalaryRowsToShow,
    }),
    [
      setSalarySearch,
      setSalaryPeriod,
      setSalarySort,
      setSalaryStatusFilter,
      clearSalaryFilters,
      clearSelection,
      openBulkActionModal,
      openBulkPaymentModal,
      canBulkActOnSalaryClaim,
      getClaimKey,
      isClaimKeySelected,
      toggleSalaryGroupSelection,
      openClaimDetail,
      buildClaimRowActionItems,
      setSalaryRowsToShow,
    ],
  )

  const overtimeRecordsVm = useMemo(
    () => ({
      search: overtimeSearch,
      period: overtimePeriod,
      sort: overtimeSort,
      statusFilter: overtimeStatusFilter,
      statusOptions: overtimeStatusOptions,
      overtimeSortOptions,
      filteredRecords: filteredOvertimeRows,
      visibleRows: visibleOvertimeRows,
      groupedRows: groupedVisibleOvertimeRows,
      rowsToShow: overtimeRowsToShow,
      totalCount: overtimeTotalCount,
      getStatusBadge,
      getStatusLabel: getOvertimeWorkflowStatusLabel,
      getPendingActionHint: getOvertimeWorkflowPendingActionHint,
      getDisplayOvertimeId,
      getStartDateTimeLabel: getOvertimeStartDateTimeLabel,
      getEndDateTimeLabel: getOvertimeEndDateTimeLabel,
      formatDate: formatOvertimeDate,
      getReviewActionConfig: getOvertimeReviewActionConfig,
    }),
    [
      overtimeSearch,
      overtimePeriod,
      overtimeSort,
      overtimeStatusFilter,
      overtimeStatusOptions,
      overtimeSortOptions,
      filteredOvertimeRows,
      visibleOvertimeRows,
      groupedVisibleOvertimeRows,
      overtimeRowsToShow,
      overtimeTotalCount,
      getStatusBadge,
      getOvertimeWorkflowStatusLabel,
      getOvertimeWorkflowPendingActionHint,
      getDisplayOvertimeId,
      getOvertimeStartDateTimeLabel,
      getOvertimeEndDateTimeLabel,
      formatOvertimeDate,
      getOvertimeReviewActionConfig,
    ],
  )

  const overtimeRecordsHandlers = useMemo(
    () => ({
      setSearch: setOvertimeSearch,
      setPeriod: setOvertimePeriod,
      setSort: setOvertimeSort,
      setStatusFilter: setOvertimeStatusFilter,
      clearFilters: clearOvertimeFilters,
      setRowsToShow: setOvertimeRowsToShow,
      approveOvertime,
      rejectOvertime,
      openOvertimeDetail,
    }),
    [
      setOvertimeSearch,
      setOvertimePeriod,
      setOvertimeSort,
      setOvertimeStatusFilter,
      clearOvertimeFilters,
      setOvertimeRowsToShow,
      approveOvertime,
      rejectOvertime,
      openOvertimeDetail,
    ],
  )

  const assignmentTabVm = useMemo(
    () => ({
      assignmentSearch,
      assignmentSort,
      assignmentSortOptions,
      assignmentTeamFilter,
      assignmentTeamOptions,
      filteredAssignmentRows,
      groupedVisibleAssignmentRows,
      assignmentRowsToShow,
      totalCount: assignmentTotalCount,
      assignmentHistory,
      isLoading: isAssignmentsLoading,
      loadError: assignmentLoadError,
      formatCurrency,
      formatDate,
      formatMonth,
      getAssignmentNetAssigned,
    }),
    [
      assignmentSearch,
      assignmentSort,
      assignmentSortOptions,
      assignmentTeamFilter,
      assignmentTeamOptions,
      filteredAssignmentRows,
      groupedVisibleAssignmentRows,
      assignmentRowsToShow,
      assignmentTotalCount,
      assignmentHistory,
      isAssignmentsLoading,
      assignmentLoadError,
      formatCurrency,
      formatDate,
      formatMonth,
      getAssignmentNetAssigned,
    ],
  )

  const assignmentTabHandlers = useMemo(
    () => ({
      setAssignmentSearch,
      setAssignmentSort,
      setAssignmentTeamFilter,
      clearAssignmentFilters,
      openCreateAssignment,
      openEditAssignment,
      openAssignmentDetail,
      resumeAssignmentDraft,
      deleteAssignmentRow,
      setAssignmentRowsToShow,
      retryLoadAssignments,
    }),
    [
      setAssignmentSearch,
      setAssignmentSort,
      setAssignmentTeamFilter,
      clearAssignmentFilters,
      openCreateAssignment,
      openEditAssignment,
      openAssignmentDetail,
      resumeAssignmentDraft,
      deleteAssignmentRow,
      setAssignmentRowsToShow,
      retryLoadAssignments,
    ],
  )

  const overtimeRatesVm = useMemo(
    () => ({
      otRateSettings,
      otRateDirty,
      formatDateTime,
    }),
    [otRateSettings, otRateDirty, formatDateTime],
  )

  const overtimeRatesHandlers = useMemo(
    () => ({
      updateOvertimeApplicabilityField,
      updateOvertimeRateField,
      updateOvertimeBaseHourField,
      updateOvertimeRoleOverrideField,
      resetOvertimeRates,
      reloadOvertimeRates,
      persistOvertimeRates,
    }),
    [
      updateOvertimeApplicabilityField,
      updateOvertimeRateField,
      updateOvertimeBaseHourField,
      updateOvertimeRoleOverrideField,
      resetOvertimeRates,
      reloadOvertimeRates,
      persistOvertimeRates,
    ],
  )

  return {
    claimDetailVm,
    claimDetailHandlers,
    claimRecordsVm,
    claimRecordsHandlers,
    salaryRecordsVm,
    salaryRecordsHandlers,
    overtimeRecordsVm,
    overtimeRecordsHandlers,
    assignmentTabVm,
    assignmentTabHandlers,
    overtimeRatesVm,
    overtimeRatesHandlers,
  }
}

export default useSalaryClaimsViewModels
