export const FRT_TRUCK_REFERENCE = {
  plateNo: 'AJG9555',
  roadTaxExpiry: '13/02/2026',
  insuranceExpiry: '13/02/2026',
  puspakomExpiry: '19/02/2026',
}

const dailySections = [
  {
    key: 'locker-01',
    title: 'LOCKER 01',
    sourceTitle: 'LOCKER 01',
    rows: [
      ['1', 'FIRE HOSE 2.5"', '6', 'status'],
      ['2', 'FIRE HOSE 1.5"', '4', 'status'],
      ['3', 'LIFEBUOY', '1', 'status'],
      ['4', 'SPINAL BOARD', '1', 'status'],
      ['5', 'FOLDABLE STRETCHER', '1', 'status'],
      ['6', 'STOKES STRETCHER', '1', 'status'],
    ],
  },
  {
    key: 'locker-02',
    title: 'LOCKER 02',
    sourceTitle: 'LOCKER 02',
    rows: [
      ['7', 'HYDRAULIC MOTOR PUMP', '1', 'status'],
      ['8', 'HYDRAULIC HOSE', '1', 'status'],
      ['9', 'HYDRAULIC CUTTER', '1', 'status'],
      ['10', 'HYDRAULIC SPREADER', '1', 'status'],
      ['11', 'HYDRAULIC COMBI TOOLS', '1', 'status'],
      ['12', 'RAM', '1', 'status'],
    ],
  },
  {
    key: 'locker-03',
    title: 'LOCKER 03',
    sourceTitle: 'LOCKER 03',
    rows: [
      ['13', 'HOSE REEL WITH NOZZLE', '1', 'status'],
      ['14', 'HOSE REEL LUG WRENCH', '1', 'status'],
      ['15', 'SPARE NOZZLE 1"', '1', 'status'],
      ['16', 'REFILLING HOSE 2.5"', '1', 'status'],
      ['17', 'HOSE RAMP', '1', 'status'],
      ['18', 'WEBBING', '1', 'status'],
      ['19', 'CONE', '2', 'status'],
    ],
  },
  {
    key: 'locker-04',
    title: 'LOCKER 04',
    sourceTitle: 'LOCKER 04',
    rows: [
      ['20', 'GODIVA FIRE PUMP', '1', 'status'],
      ['21', 'WATER TANK LEVEL', '4', 'status'],
      ['22', 'FOAM LEVEL (A)', '2', 'status'],
      ['23', 'FOAM LEVEL (B)', '1', 'status'],
      ['24', 'WATER OUTLET 2.5"', '3', 'status'],
      ['25', 'WATER INLET 2.5"', '1', 'status'],
      ['26', 'FOAM OUTLET CAFS 2.5"', '1', 'status'],
      ['27', 'WATER SUCTION INLET 4"', '1', 'status'],
      ['28', 'ROOF MONITOR', '1', 'status'],
      ['29', 'ROOF MONITOR R/CONTROLLER', '1', 'status'],
      ['30', 'WATER TANK MANHOLE LID', '1', 'status'],
      ['31', 'FOAM TANK MANHOLE LID', '2', 'status'],
      ['32', 'ROOF FIX TOOLBOX', '1', 'status'],
    ],
  },
  {
    key: 'locker-05',
    title: 'LOCKER 05',
    sourceTitle: 'LOCKER 05',
    rows: [
      ['33', 'DIVIDING BREECHING (CONTROLLER)', '2', 'status'],
      ['34', 'DIVIDING BREECHING', '1', 'status'],
      ['35', 'COLLECTING BREECHING', '2', 'status'],
      ['36', 'FIRE EXTINGUISHER ABC 6KG', '1', 'status'],
      ['37', 'HANDLINE NOZZLE', '2', 'status'],
      ['38', 'PLAIN NOZZLE', '2', 'status'],
      ['39', '4" INLET COLLECTING CAP', '1', 'status'],
      ['40', 'HYDRANT ADAPTOR', '1', 'status'],
      ['41', 'HARD SUCTION WRENCH SPANNER', '1', 'status'],
      ['42', 'HYDRANT KEY', '1', 'status'],
      ['43', 'AFFF (25 L)', '1', 'status'],
      ['44', 'FOAM INDUCTOR WITH TUBE', '1', 'status'],
      ['45', 'FOAM MAKING BRANCH', '1', 'status'],
    ],
  },
  {
    key: 'locker-06',
    title: 'LOCKER 06',
    sourceTitle: 'LOCKER 06',
    rows: [
      ['46', 'SHACKLE WITH CHAIN', '1', 'status'],
      ['47', 'SHACKLE WITH HOOK', '1', 'status'],
      ['48', 'SHOVEL', '2', 'status'],
      ['49', 'AXE', '1', 'status'],
      ['50', 'AFFF FOAM (SPARE)', '1', 'status'],
    ],
  },
  {
    key: 'locker-07',
    title: 'LOCKER 07',
    sourceTitle: 'LOCKER 07',
    rows: [['51', 'SCBA SET (SPARE)', '4', 'status']],
  },
  {
    key: 'locker-08',
    title: 'LOCKER 08',
    sourceTitle: 'LOCKER 08',
    rows: [
      ['52', 'CHOKE', '2', 'status'],
      ['53', 'WORKING HARNESS', '1', 'status'],
      ['54', 'YELLOW ROPE', '1', 'status'],
      ['55', 'LIFE JACKET', '2', 'status'],
    ],
  },
  {
    key: 'fire-truck',
    title: 'FIRE TRUCK',
    sourceTitle: 'FIRE TRUCK',
    rows: [
      ['56', 'RADIATOR LEVEL GAUGE', 'N/A', 'status'],
      ['57', 'BATTERY WATER LEVEL GAUGE', 'N/A', 'status'],
      ['58', 'ENGINE OIL LEVEL GAUGE', 'N/A', 'status'],
      ['59', 'RADIO COMMUNICATION', 'N/A', 'status'],
      ['60', 'AIR CONDITIONER', 'N/A', 'status'],
      ['61', 'HORN', 'N/A', 'status'],
      ['62', 'SIDE MIRROR', 'N/A', 'status'],
      ['63', 'BACK MIRROR', 'N/A', 'status'],
      ['64', 'REVERSE CAMERA', 'N/A', 'status'],
      ['65', 'PANEL CONDITION', 'N/A', 'status'],
      ['66', 'FIXED PA SYSTEM (SIREN)', 'N/A', 'status'],
      ['67', 'AIR HORN', 'N/A', 'status'],
      ['68', 'BRAKE SYSTEM', 'N/A', 'status'],
      ['69', 'CABIN LIGHT', 'N/A', 'status'],
      ['70', 'HEAD LAMP', 'N/A', 'status'],
      ['71', 'BUMPER FOG LIGHT', 'N/A', 'status'],
      ['72', 'BACK LAMP', 'N/A', 'status'],
      ['73', 'BREAK LAMP', 'N/A', 'status'],
      ['74', 'SIGNAL LAMP', 'N/A', 'status'],
      ['75', 'HAZARD LAMP', 'N/A', 'status'],
      ['76', 'REAR FLASHLIGHT', 'N/A', 'status'],
      ['77', 'LOCKER LAMP', 'N/A', 'status'],
      ['78', 'EMERGENCY LIGHT BAR', 'N/A', 'status'],
      ['79', 'DASH MOUNTED SEARCH LIGHT', 'N/A', 'status'],
      ['80', 'WINDSHIELD (HEAD TOP)', 'N/A', 'status'],
      ['81', 'FIRST AID BOX', '1', 'status'],
      ['82', 'RENAULT MANUAL BOOK', '1', 'status'],
      ['83', 'EMERGENCY TRIANGLE', '1', 'status'],
      ['84', 'MANUAL HAND JACK (10T)', '1', 'status'],
      ['85', 'HAND PUMP GREASER', '1', 'status'],
      ['86', 'TYRE PRESSURE HOSE', '1', 'status'],
      ['87', 'PNEUMATIC HOSES', '1', 'status'],
      ['88', 'WINCH ADAPTOR ACCESSORIES', '1', 'status'],
      ['89', 'TRUCK HEAD LIFT SPANNER', '1', 'status'],
      ['90', 'OVERALL BODY', 'N/A', 'status'],
      ['91', 'MILEAGE (ODOMETER)', '', 'reading'],
      ['92', 'FUEL LEVEL (%)', '', 'reading'],
    ],
  },
]

const oneOffSections = [
  {
    key: 'truck-checklist',
    title: 'TRUCK CHECKLIST',
    sourceTitle: 'TRUCK CHECKLIST',
    rows: [
      ['1', 'POWER WINDOW'],
      ['2', 'HEAD LAMP'],
      ['3', 'BACK LAMP'],
      ['4', 'BREAK LAMP'],
      ['5', 'LIGHT BAR'],
      ['6', 'HAZARD LAMP'],
      ['7', 'ACCESS LADDER'],
      ['8', 'TYRE'],
      ['9', 'SPARE TYRE'],
      ['10', 'FIRE MONITOR'],
      ['11', 'FIRE PUMP'],
      ['12', 'HYDRAULIC HOSE'],
      ['13', 'SIGNAL LAMP'],
      ['14', 'WIPER'],
      ['15', 'COMPARTMENT LIGHT'],
      ['16', 'ELECTRONIC SIREN'],
      ['17', 'AIR HORN'],
      ['18', 'HORN'],
      ['19', 'BATTERY'],
      ['20', 'SPOTLIGHT'],
      ['21', 'BODY AND CABIN'],
      ['22', 'SIDE MIRROR'],
      ['23', 'BREAK SYSTEM'],
    ],
  },
  {
    key: 'locker-no-01',
    title: 'LOCKER NO 01',
    sourceTitle: 'LOCKER NO 01',
    rows: [
      ['24', '2.5 INCH FIRE HOSE : 1'],
      ['25', '1.5 INCH FIRE HOSE : 5'],
    ],
  },
  {
    key: 'locker-no-02',
    title: 'LOCKER NO 02',
    sourceTitle: 'LOCKER NO 02',
    rows: [
      ['26', '2.5 INCH FIRE HOSE : 6'],
      ['27', '1.5 INCH FIRE HOSE'],
    ],
  },
  {
    key: 'locker-no-03',
    title: 'LOCKER NO 03',
    sourceTitle: 'LOCKER NO 03',
    rows: [
      ['28', 'HOSE RAM : 2'],
      ['29', 'HOSE REEL : 1'],
      ['30', 'SUCTION ADAPTER : 1'],
    ],
  },
  {
    key: 'locker-no-04',
    title: 'LOCKER NO 04',
    sourceTitle: 'LOCKER NO 04',
    rows: [
      ['31', 'GODIVA FIRE PUMP : ONE SET'],
      ['32', 'PRIMER : ONE SET'],
      ['33', 'PRESSURE GAUGE : 3'],
      ['34', 'OUTLET : 4'],
      ['35', 'INLET : 2'],
      ['36', 'ELECTRONIC PANEL : ONE SET'],
    ],
  },
  {
    key: 'locker-no-05',
    title: 'LOCKER NO 05',
    sourceTitle: 'LOCKER NO 05',
    rows: [
      ['37', 'HYDRAULIC CUTTER : 1'],
      ['38', 'HYDRAULIC MOTOR PUMP : 1'],
      ['39', 'HYDRAULIC HOSE : 1'],
    ],
  },
  {
    key: 'locker-no-06',
    title: 'LOCKER NO 06',
    sourceTitle: 'LOCKER NO 06',
    rows: [
      ['40', 'FIRE HELMET : 4'],
      ['41', 'FIRE SUIT : 4'],
    ],
  },
  {
    key: 'locker-no-07',
    title: 'LOCKER NO 07',
    sourceTitle: 'LOCKER NO 07',
    rows: [
      ['42', 'HARD SUCTION HOSE : 4'],
      ['43', 'TOOLBOX : 1'],
      ['44', 'FIRE EXTINGUISHER : 2'],
    ],
  },
  {
    key: 'crew-cabin',
    title: 'CREW CABIN',
    sourceTitle: 'CREW CABIN',
    rows: [
      ['45', 'BA SET : 4'],
      ['46', 'RADIO SET : 1'],
    ],
  },
]

export const FRT_REFERENCE = {
  sourceWorkbook: 'report-reference/VMM FRT Daily Inspection Checklist.xlsx',
  supportedMainLocations: ['FIRE TRUCK'],
  truckReference: FRT_TRUCK_REFERENCE,
  dailyFields: [
    { key: 'rowNumber', label: 'No.', sourceLabel: 'NO' },
    { key: 'location', label: 'Group', sourceLabel: 'LOCATION' },
    { key: 'equipment', label: 'Vehicle / Equipment', sourceLabel: 'VEHICLE/EQUIPMENT' },
    { key: 'quantity', label: 'Qty', sourceLabel: 'QTY' },
    { key: 'status', label: 'Status', sourceLabel: 'Daily status' },
    { key: 'readingValue', label: 'Reading', sourceLabel: 'Selected day reading' },
    { key: 'remarks', label: 'Remarks', sourceLabel: 'Issue remarks' },
  ],
  oneOffFields: [
    { key: 'rowNumber', label: 'No.', sourceLabel: 'NO' },
    { key: 'location', label: 'Group', sourceLabel: 'LOCATION' },
    { key: 'equipment', label: 'Item', sourceLabel: 'ITEM' },
    { key: 'condition', label: 'Condition', sourceLabel: 'STATUS' },
    { key: 'remarks', label: 'Remarks', sourceLabel: 'REMARK' },
  ],
  dailySections,
  oneOffSections,
}
