// Generated from vmecc-backend/database/seeders/data/fire_extinguishers.json.
// Keep this as a frontend fallback for site-location selectors when API/cache is unavailable.
export const SITE_ZONE_LOCATION_ROWS = [
  {
    value: '1',
    title: '1',
    subLocations: [
      {
        value: 'Manjung Hub',
        title: 'Manjung Hub',
        subLocations: [
          { value: 'Reception', title: 'Reception' },
          { value: 'Infront Auditorium', title: 'Infront Auditorium' },
          { value: 'Infront H.Room', title: 'Infront H.Room' },
          { value: 'Opreration LAB', title: 'Opreration LAB' },
          { value: 'Training Utility', title: 'Training Utility' },
          { value: 'Vulcanizing LAB', title: 'Vulcanizing LAB' },
          { value: 'Infront Nursing Room', title: 'Infront Nursing Room' },
          { value: 'Relaxing Area', title: 'Relaxing Area' },
          { value: 'Training Room 1', title: 'Training Room 1' },
          { value: 'Infront Training Room 1', title: 'Infront Training Room 1' },
          { value: 'Training Room 2', title: 'Training Room 2' },
          { value: 'Cafeteria', title: 'Cafeteria' },
          { value: 'Male Toilet', title: 'Male Toilet' },
          { value: 'Infront meeting Room 3', title: 'Infront meeting Room 3' },
          { value: 'Admin', title: 'Admin' },
          { value: 'Near Emergency Exit Door', title: 'Near Emergency Exit Door' },
        ],
      },
      {
        value: 'Canteen',
        title: 'Canteen',
        subLocations: [
          { value: 'Canteen', title: 'Canteen' },
          { value: 'Dry Store', title: 'Dry Store' },
        ],
      },
      {
        value: 'Generator House',
        title: 'Generator House',
        subLocations: [{ value: 'Generator', title: 'Generator' }],
      },
      {
        value: 'Gate House',
        title: 'Gate House',
        subLocations: [{ value: 'Gate House', title: 'Gate House' }],
      },
      {
        value: 'Security Office',
        title: 'Security Office',
        subLocations: [{ value: 'SCR', title: 'SCR' }],
      },
      {
        value: 'Water Room',
        title: 'Water Room',
        subLocations: [{ value: 'Water Room', title: 'Water Room' }],
      },
      {
        value: 'ID Pass Office',
        title: 'ID Pass Office',
        subLocations: [
          { value: 'ID Main Entrance', title: 'ID Main Entrance' },
          { value: 'Induction Room', title: 'Induction Room' },
          { value: 'Pass Inssurance', title: 'Pass Inssurance' },
          { value: 'Store', title: 'Store' },
        ],
      },
      {
        value: 'IT Server Room',
        title: 'IT Server Room',
        subLocations: [{ value: 'IT Main Entrance', title: 'IT Main Entrance' }],
      },
      {
        value: 'First Aid Station',
        title: 'First Aid Station',
        subLocations: [
          { value: 'Clinic', title: 'Clinic' },
          { value: 'Treatment Room', title: 'Treatment Room' },
        ],
      },
      {
        value: 'Fire Station',
        title: 'Fire Station',
        subLocations: [
          { value: 'Bay', title: 'Bay' },
          { value: 'FRT', title: 'FRT' },
        ],
      },
      {
        value: 'Transport Office',
        title: 'Transport Office',
        subLocations: [{ value: 'VMM', title: 'VMM' }],
      },
      {
        value: 'Training Center 2',
        title: 'Training Center 2',
        subLocations: [
          { value: 'DOJO Room', title: 'DOJO Room' },
          { value: 'Passageway', title: 'Passageway' },
          { value: 'Office Room', title: 'Office Room' },
        ],
      },
      {
        value: 'Sustaining Investment Office',
        title: 'Sustaining Investment Office',
        subLocations: [
          { value: 'Office', title: 'Office' },
          { value: 'Document Room', title: 'Document Room' },
          { value: 'Secure Storage Room', title: 'Secure Storage Room' },
          { value: 'Server Room', title: 'Server Room' },
        ],
      },
      {
        value: 'Vale Eco Centre',
        title: 'Vale Eco Centre',
        subLocations: [
          { value: 'Pantry Room', title: 'Pantry Room' },
          { value: 'Server Room', title: 'Server Room' },
        ],
      },
      {
        value: 'TSTP(Room)',
        title: 'TSTP(Room)',
        subLocations: [{ value: 'Inside Room', title: 'Inside Room' }],
      },
    ],
  },
  {
    value: 'Others',
    title: 'Others',
    subLocations: [
      {
        value: 'Vehicle',
        title: 'Vehicle',
        subLocations: [{ value: 'VMM', title: 'VMM' }],
      },
      {
        value: 'Payloader',
        title: 'Payloader',
        subLocations: [
          { value: 'AKY 3912', title: 'AKY 3912' },
          { value: 'AKY 3914', title: 'AKY 3914' },
          { value: 'AKY 3918', title: 'AKY 3918' },
          { value: 'AKY 3920', title: 'AKY 3920' },
        ],
      },
    ],
  },
  {
    value: '2',
    title: '2',
    subLocations: [
      {
        value: 'Cafetaria',
        title: 'Cafetaria',
        subLocations: [
          { value: 'Dining hall', title: 'Dining hall' },
          { value: 'Food serving area', title: 'Food serving area' },
        ],
      },
      {
        value: 'Central Control Room (CCR)',
        title: 'Central Control Room (CCR)',
        subLocations: [
          { value: 'Ground Floor - Lobby', title: 'Ground Floor - Lobby' },
          { value: 'Ground Floor - Office', title: 'Ground Floor - Office' },
          { value: 'Infront IT Panel Room', title: 'Infront IT Panel Room' },
          { value: '1st Lobby', title: '1st Lobby' },
          {
            value: 'Level 1-Control Room (Depan Pintu)',
            title: 'Level 1-Control Room (Depan Pintu)',
          },
          { value: 'Infront New Server Room', title: 'Infront New Server Room' },
          { value: 'Level 1 - Control Room', title: 'Level 1 - Control Room' },
          { value: 'Level 1 Control Room 1', title: 'Level 1 Control Room 1' },
          { value: 'Level 2 - 2nd Lobby', title: 'Level 2 - 2nd Lobby' },
          { value: 'Level 2 - Pantry', title: 'Level 2 - Pantry' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'HSE OFFICE', title: 'HSE OFFICE' },
          { value: 'Roof Top', title: 'Roof Top' },
        ],
      },
      {
        value: 'Warehouse',
        title: 'Warehouse',
        subLocations: [
          { value: 'Warehouse Office', title: 'Warehouse Office' },
          { value: 'Warehouse Yard', title: 'Warehouse Yard' },
          { value: 'Office Hydraulic & Lubrication', title: 'Office Hydraulic & Lubrication' },
          { value: 'VAC Room', title: 'VAC Room' },
          { value: 'Lubrication Storaged Shed', title: 'Lubrication Storaged Shed' },
          { value: 'Warehouse Cool Room', title: 'Warehouse Cool Room' },
          { value: 'Asset monitoring center (CMA)', title: 'Asset monitoring center (CMA)' },
        ],
      },
      {
        value: 'Workshop',
        title: 'Workshop',
        subLocations: [
          { value: 'W/Shop Yard', title: 'W/Shop Yard' },
          { value: 'W/shop Bay', title: 'W/shop Bay' },
          { value: 'Hot Work Section', title: 'Hot Work Section' },
          { value: 'Tool Room', title: 'Tool Room' },
          { value: 'Compressor Room', title: 'Compressor Room' },
        ],
      },
      {
        value: 'Maintenance Office',
        title: 'Maintenance Office',
        subLocations: [
          { value: 'GL - Lobby', title: 'GL - Lobby' },
          { value: 'GL - Office', title: 'GL - Office' },
          { value: 'GL - Server Room', title: 'GL - Server Room' },
          { value: 'Level 1', title: 'Level 1' },
        ],
      },
      {
        value: 'Potable Water Pump House',
        title: 'Potable Water Pump House',
        subLocations: [{ value: 'Portable Water Pump House', title: 'Portable Water Pump House' }],
      },
      {
        value: 'Main Sub Station',
        title: 'Main Sub Station',
        subLocations: [
          { value: '275KV CP ROOM', title: '275KV CP ROOM' },
          { value: 'Battery Room', title: 'Battery Room' },
          { value: 'Communacation Room', title: 'Communacation Room' },
          { value: 'LV / Switchgear Room', title: 'LV / Switchgear Room' },
          { value: '33KV Switchgear Room', title: '33KV Switchgear Room' },
          { value: 'Cable Room', title: 'Cable Room' },
        ],
      },
    ],
  },
  {
    value: '3',
    title: '3',
    subLocations: [
      {
        value: 'ER-01',
        title: 'ER-01',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Boom Area', title: 'Boom Area' },
          { value: 'Cabin Crew', title: 'Cabin Crew' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'LV Room', title: 'LV Room' },
          { value: 'Transformer Room', title: 'Transformer Room' },
          { value: 'Upper E.Room', title: 'Upper E.Room' },
        ],
      },
      {
        value: 'ER-02',
        title: 'ER-02',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Boom Area', title: 'Boom Area' },
          { value: 'Operator Cabin', title: 'Operator Cabin' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'LV Room', title: 'LV Room' },
          { value: 'Transformer Room', title: 'Transformer Room' },
          { value: 'Upper E.Room', title: 'Upper E.Room' },
        ],
      },
      {
        value: 'EP-03',
        title: 'EP-03',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Boom Area', title: 'Boom Area' },
          { value: 'Operator Cabin', title: 'Operator Cabin' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'LV Room', title: 'LV Room' },
          { value: 'Transformer Room', title: 'Transformer Room' },
        ],
      },
      {
        value: 'ER-04',
        title: 'ER-04',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Boom Area', title: 'Boom Area' },
          { value: 'Operator Cabin', title: 'Operator Cabin' },
          { value: 'LV Room', title: 'LV Room' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'Transformer Room', title: 'Transformer Room' },
          { value: 'Upper E.Room', title: 'Upper E.Room' },
        ],
      },
      {
        value: 'RC-05',
        title: 'RC-05',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Pond Boom Area', title: 'Pond Boom Area' },
          { value: 'CCR Boom area', title: 'CCR Boom area' },
          { value: 'Operator Cabin', title: 'Operator Cabin' },
          { value: 'LV Room', title: 'LV Room' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'Transformer Room', title: 'Transformer Room' },
          { value: 'Upper E.Room', title: 'Upper E.Room' },
        ],
      },
      {
        value: 'CT-15',
        title: 'CT-15',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
        ],
      },
      {
        value: 'CT-17',
        title: 'CT-17',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
        ],
      },
      {
        value: 'CT-18',
        title: 'CT-18',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
        ],
      },
      {
        value: 'CT-19',
        title: 'CT-19',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
        ],
      },
      {
        value: 'Service Water Pump House',
        title: 'Service Water Pump House',
        subLocations: [{ value: 'New Pump House', title: 'New Pump House' }],
      },
      {
        value: 'Secondary Sub Station - 02 (Yard)',
        title: 'Secondary Sub Station - 02 (Yard)',
        subLocations: [
          { value: 'Feeder Room', title: 'Feeder Room' },
          { value: 'ACC Room', title: 'ACC Room' },
          { value: 'Battery Room', title: 'Battery Room' },
        ],
      },
      {
        value: 'Secondary Sub Station - 03 (Yard)',
        title: 'Secondary Sub Station - 03 (Yard)',
        subLocations: [
          { value: 'LV Room', title: 'LV Room' },
          { value: 'MV Room', title: 'MV Room' },
          { value: 'Battery Room', title: 'Battery Room' },
        ],
      },
    ],
  },
  {
    value: '4 & 4B',
    title: '4 & 4B',
    subLocations: [
      {
        value: 'Storm Water Pump House',
        title: 'Storm Water Pump House',
        subLocations: [],
      },
      {
        value: 'Storm Water 2',
        title: 'Storm Water 2',
        subLocations: [],
      },
      {
        value: 'Storm Water 1',
        title: 'Storm Water 1',
        subLocations: [],
      },
      {
        value: 'Fire Water System Pump House',
        title: 'Fire Water System Pump House',
        subLocations: [],
      },
      {
        value: 'Raw Water Pump House 02',
        title: 'Raw Water Pump House 02',
        subLocations: [],
      },
      {
        value: 'Raw Water Pump House 01',
        title: 'Raw Water Pump House 01',
        subLocations: [],
      },
      {
        value: 'Recirculating Pond Pump House',
        title: 'Recirculating Pond Pump House',
        subLocations: [],
      },
      {
        value: 'Sewage Treatment Plant',
        title: 'Sewage Treatment Plant',
        subLocations: [{ value: 'Mini Laboratory', title: 'Mini Laboratory' }],
      },
      {
        value: 'Waste Water Treatment Plant',
        title: 'Waste Water Treatment Plant',
        subLocations: [],
      },
      {
        value: 'Laboratory',
        title: 'Laboratory',
        subLocations: [
          { value: 'Entrance', title: 'Entrance' },
          { value: 'Lobby', title: 'Lobby' },
          { value: 'Sample Preparation Area', title: 'Sample Preparation Area' },
          { value: 'Sample Archive Storage', title: 'Sample Archive Storage' },
          { value: 'Electrical Room', title: 'Electrical Room' },
          { value: 'Balance and Pulp Storage', title: 'Balance and Pulp Storage' },
          { value: 'IT Room', title: 'IT Room' },
          { value: 'Borate Lab', title: 'Borate Lab' },
          { value: 'XRF Lab', title: 'XRF Lab' },
          { value: 'Outside Lab', title: 'Outside Lab' },
          { value: 'General Store', title: 'General Store' },
          { value: 'Analytical Room', title: 'Analytical Room' },
          { value: 'Regent Storage', title: 'Regent Storage' },
        ],
      },
      {
        value: 'Central Control Room 2 (CCR2)',
        title: 'Central Control Room 2 (CCR2)',
        subLocations: [
          { value: 'Enterance', title: 'Enterance' },
          { value: 'W/Station', title: 'W/Station' },
          { value: 'CCR 2', title: 'CCR 2' },
          { value: 'Server Room', title: 'Server Room' },
          { value: 'Level 1', title: 'Level 1' },
        ],
      },
      {
        value: 'Maintenance Execution Office/LOTO Cabin',
        title: 'Maintenance Execution Office/LOTO Cabin',
        subLocations: [
          { value: 'LOTO Cabin 1', title: 'LOTO Cabin 1' },
          { value: 'M E O', title: 'M E O' },
        ],
      },
      {
        value: 'CT-08',
        title: 'CT-08',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4', title: 'Level 4' },
        ],
      },
      {
        value: 'CT-09',
        title: 'CT-09',
        subLocations: [
          { value: 'Ground Level', title: 'Ground Level' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4', title: 'Level 4' },
        ],
      },
      {
        value: 'CT-03',
        title: 'CT-03',
        subLocations: [
          { value: 'Ground Floor', title: 'Ground Floor' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
        ],
      },
      {
        value: 'CT-19A',
        title: 'CT-19A',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
        ],
      },
      {
        value: 'Secondary Sub Station - 01 (Yard)',
        title: 'Secondary Sub Station - 01 (Yard)',
        subLocations: [
          { value: 'Switchboard Area', title: 'Switchboard Area' },
          { value: 'Battery Room', title: 'Battery Room' },
          { value: 'HVAC', title: 'HVAC' },
        ],
      },
      {
        value: 'TR-13',
        title: 'TR-13',
        subLocations: [
          { value: 'Stairs - 1 (Pond)', title: 'Stairs - 1 (Pond)' },
          { value: 'Stairs - 1 (Villa)', title: 'Stairs - 1 (Villa)' },
          { value: 'Stairs - 2 (Pond)', title: 'Stairs - 2 (Pond)' },
          { value: 'Stairs - 2 (Villa)', title: 'Stairs - 2 (Villa)' },
          { value: 'Stairs - 3 (Pond)', title: 'Stairs - 3 (Pond)' },
          { value: 'Stairs - 3 (Villa)', title: 'Stairs - 3 (Villa)' },
          { value: 'Stair - 4 (Pond)', title: 'Stair - 4 (Pond)' },
          { value: 'Stair - 4 (Villa)', title: 'Stair - 4 (Villa)' },
          { value: 'Stair - 5 (Pond)', title: 'Stair - 5 (Pond)' },
          { value: 'Stair - 5 (Villa)', title: 'Stair - 5 (Villa)' },
        ],
      },
    ],
  },
  {
    value: '5',
    title: '5',
    subLocations: [
      {
        value: 'Port Office',
        title: 'Port Office',
        subLocations: [
          { value: 'Galley', title: 'Galley' },
          { value: 'Male Surau', title: 'Male Surau' },
          { value: 'Port Office Lobby', title: 'Port Office Lobby' },
          { value: 'Level 1 -Office', title: 'Level 1 -Office' },
          { value: 'Level 1 - Locker Room', title: 'Level 1 - Locker Room' },
          { value: 'LOTO Cabin 3', title: 'LOTO Cabin 3' },
        ],
      },
      {
        value: 'CT-01',
        title: 'CT-01',
        subLocations: [
          { value: 'Level 1 (Stair)', title: 'Level 1 (Stair)' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2 (Stair)', title: 'Level 2 (Stair)' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3 (Stair)', title: 'Level 3 (Stair)' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4 (Stair)', title: 'Level 4 (Stair)' },
          { value: 'Level 4', title: 'Level 4' },
        ],
      },
      {
        value: 'Minor Export Wharf',
        title: 'Minor Export Wharf',
        subLocations: [
          { value: 'E-07', title: 'E-07' },
          { value: 'E-15', title: 'E-15' },
          { value: 'E-21', title: 'E-21' },
          { value: 'E-27', title: 'E-27' },
          { value: 'OUTER TUG WHARF', title: 'OUTER TUG WHARF' },
        ],
      },
      {
        value: 'DN-10',
        title: 'DN-10',
        subLocations: [
          { value: 'Lift', title: 'Lift' },
          { value: 'Infront lift', title: 'Infront lift' },
          { value: 'Level 1 (Generator room)', title: 'Level 1 (Generator room)' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4', title: 'Level 4' },
          { value: 'Cabin operator', title: 'Cabin operator' },
          { value: 'Level 4 (Inside E-room)', title: 'Level 4 (Inside E-room)' },
          { value: 'Level 4 (Outside E-room)', title: 'Level 4 (Outside E-room)' },
        ],
      },
      {
        value: 'DN-11',
        title: 'DN-11',
        subLocations: [
          { value: 'Infront Lift', title: 'Infront Lift' },
          { value: 'Lift', title: 'Lift' },
          { value: 'Level 1(Generator room)', title: 'Level 1(Generator room)' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4', title: 'Level 4' },
          { value: 'Level 4 (Inside E-room)', title: 'Level 4 (Inside E-room)' },
          { value: 'Level 4 (Outside E-room)', title: 'Level 4 (Outside E-room)' },
          { value: 'Cabin operator', title: 'Cabin operator' },
        ],
      },
      {
        value: 'DN-12',
        title: 'DN-12',
        subLocations: [
          { value: 'Infront lift', title: 'Infront lift' },
          { value: 'Lift', title: 'Lift' },
          { value: 'Level 1 (Generator room)', title: 'Level 1 (Generator room)' },
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Level 3', title: 'Level 3' },
          { value: 'Level 4', title: 'Level 4' },
          { value: 'Cabin operator', title: 'Cabin operator' },
        ],
      },
      {
        value: 'Major Import Wharf',
        title: 'Major Import Wharf',
        subLocations: [
          { value: 'J25', title: 'J25' },
          { value: 'J31', title: 'J31' },
          { value: 'J37', title: 'J37' },
          { value: 'J43', title: 'J43' },
          { value: 'J46', title: 'J46' },
          { value: 'INNER TUG WHARF', title: 'INNER TUG WHARF' },
        ],
      },
      {
        value: 'CN-01',
        title: 'CN-01',
        subLocations: [
          { value: 'Level 1', title: 'Level 1' },
          { value: 'Level 2', title: 'Level 2' },
          { value: 'Transfer Tower', title: 'Transfer Tower' },
          { value: 'Lower LV Room', title: 'Lower LV Room' },
          { value: 'Mechanical Room', title: 'Mechanical Room' },
          { value: 'Upper MV Room', title: 'Upper MV Room' },
          { value: 'Cabin', title: 'Cabin' },
        ],
      },
      {
        value: 'Secondary Sub Station - 01 (Port)',
        title: 'Secondary Sub Station - 01 (Port)',
        subLocations: [
          { value: 'LV MCC Room', title: 'LV MCC Room' },
          { value: 'Battery Room', title: 'Battery Room' },
          { value: 'MV Switch Gear', title: 'MV Switch Gear' },
          { value: 'Transformer', title: 'Transformer' },
          { value: 'Power Transformer', title: 'Power Transformer' },
          { value: 'Dist. Transformer', title: 'Dist. Transformer' },
        ],
      },
      {
        value: 'Secondary Sub Station - 02 (Port)',
        title: 'Secondary Sub Station - 02 (Port)',
        subLocations: [
          { value: 'MV Room (Panel)', title: 'MV Room (Panel)' },
          { value: 'LV Room (Panel)', title: 'LV Room (Panel)' },
          { value: 'Battery Room', title: 'Battery Room' },
          { value: 'Power Transformer Room 1', title: 'Power Transformer Room 1' },
          { value: 'Power Transformer Room 2', title: 'Power Transformer Room 2' },
          { value: 'Distribution Transformer', title: 'Distribution Transformer' },
        ],
      },
      {
        value: 'TR11',
        title: 'TR11',
        subLocations: [
          { value: 'Outer-T01', title: 'Outer-T01' },
          { value: 'Outer-T15', title: 'Outer-T15' },
          { value: 'Inner-T15', title: 'Inner-T15' },
          { value: 'Outer-T41', title: 'Outer-T41' },
          { value: 'Inner-T41', title: 'Inner-T41' },
          { value: 'Outer-T63', title: 'Outer-T63' },
          { value: 'Inner-T63', title: 'Inner-T63' },
          { value: 'Outer-T-PP', title: 'Outer-T-PP' },
          { value: 'Inner-T-PP', title: 'Inner-T-PP' },
        ],
      },
      {
        value: 'TR-01 (Export)',
        title: 'TR-01 (Export)',
        subLocations: [
          { value: 'Outer-T-C-12.5', title: 'Outer-T-C-12.5' },
          { value: 'Inner-T-C-12.5', title: 'Inner-T-C-12.5' },
          { value: 'Outer-L2', title: 'Outer-L2' },
        ],
      },
    ],
  },
  {
    value: '6',
    title: '6',
    subLocations: [
      {
        value: 'Old Warehouse',
        title: 'Old Warehouse',
        subLocations: [
          { value: 'Old Warehouse', title: 'Old Warehouse' },
          { value: 'Kasturi Store', title: 'Kasturi Store' },
          { value: 'Office', title: 'Office' },
        ],
      },
      {
        value: 'Centre of Material Disposal',
        title: 'Centre of Material Disposal',
        subLocations: [
          { value: 'Pantry', title: 'Pantry' },
          { value: 'Office', title: 'Office' },
          { value: 'Storage Area', title: 'Storage Area' },
          { value: 'Store Room', title: 'Store Room' },
          { value: 'Cool Room', title: 'Cool Room' },
        ],
      },
      {
        value: 'Diesel Skid Tank',
        title: 'Diesel Skid Tank',
        subLocations: [{ value: 'Skid Tank', title: 'Skid Tank' }],
      },
      {
        value: 'Core Facilities',
        title: 'Core Facilities',
        subLocations: [{ value: 'Core Facilities', title: 'Core Facilities' }],
      },
      {
        value: 'Electrical Waste Segregation Area',
        title: 'Electrical Waste Segregation Area',
        subLocations: [{ value: 'Segregation Area', title: 'Segregation Area' }],
      },
      {
        value: 'Gas Storage',
        title: 'Gas Storage',
        subLocations: [{ value: 'Storage area', title: 'Storage area' }],
      },
    ],
  },
]
