import React from 'react'
import { CNavGroup, CNavItem, CNavTitle } from '@coreui/react'
import {
  Bell,
  BookOpen,
  CalendarDays,
  Check,
  Clock3,
  ClipboardList,
  Dumbbell,
  FileText,
  LayoutDashboard,
  LayoutGrid,
  MessageSquareText,
  MousePointer,
  Palette,
  PieChart,
  Settings,
  Sparkles,
  Text,
  TriangleAlert,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Wrench,
} from 'lucide-react'

const shipCheckBadge = {
  text: <Check size={11} color="#22c55e" strokeWidth={3} />,
  className: 'bg-transparent border-0 p-0 shadow-none',
}

const _nav = [
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <LayoutDashboard className="nav-icon" size={20} />,
    badge: {
      color: 'info',
      text: 'NEW',
    },
  },
  {
    component: CNavItem,
    name: 'Messages',
    to: '/messages',
    icon: <MessageSquareText className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavTitle,
    name: 'Self Service',
  },
  {
    component: CNavItem,
    name: 'Payroll',
    to: '/payroll',
    icon: <Wallet className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Overtime',
    to: '/overtime',
    icon: <Clock3 className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Leave',
    to: '/leave',
    icon: <CalendarDays className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavTitle,
    name: 'INSPECTION',
  },
  {
    component: CNavItem,
    name: 'Inspect Area',
    to: '/inspection/new',
    matchPrefix: ['/inspection'],
    icon: <ClipboardList className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'REPORTS',
  },
  {
    component: CNavItem,
    name: 'ERCO',
    to: '/report/erco/new',
    matchPrefix: ['/report/erco'],
    icon: <TriangleAlert className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Drill',
    to: '/report/drill/new',
    matchPrefix: ['/report/drill'],
    icon: <Wrench className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Fitness Test',
    to: '/report/fitness-test/new',
    matchPrefix: ['/report/fitness-test'],
    icon: <Dumbbell className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'System Admin',
  },
  {
    component: CNavItem,
    name: 'Users',
    to: '/admin/users',
    icon: <Users className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Audit',
    to: '/admin/audit',
    icon: <ClipboardList className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Settings',
    to: '/settings',
    icon: <Settings className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavTitle,
    name: 'Staff',
  },
  {
    component: CNavItem,
    name: 'Staff Directory',
    to: '/staff/details',
    icon: <UserRound className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Leave Management',
    to: '/staff/leave-management',
    icon: <CalendarDays className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Overtime Management',
    to: '/staff/overtime-management',
    icon: <Clock3 className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavTitle,
    name: 'Team',
  },
  {
    component: CNavItem,
    name: 'Team Directory',
    to: '/team/details',
    icon: <UsersRound className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Roster Management',
    to: '/roster/overview',
    icon: <LayoutGrid className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavItem,
    name: 'Shift Settings',
    to: '/staff/shift-settings',
    icon: <Settings className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavTitle,
    name: 'Financial',
  },
  {
    component: CNavItem,
    name: 'Salary & Claims',
    badge: shipCheckBadge,
    to: '/staff/salary-claims/salary',
    matchPrefix: [
      '/staff/salary-claims/claims',
      '/staff/salary-claims/salary',
      '/staff/salary-claims/claim',
      '/staff/salary-claims/overtime',
    ],
    icon: <Wallet className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Salary Settings',
    to: '/staff/set-salary/set-salary',
    matchPrefix: ['/staff/set-salary'],
    icon: <Settings className="nav-icon" size={20} />,
    badge: shipCheckBadge,
  },
  {
    component: CNavGroup,
    name: 'Reference',
    icon: <Sparkles className="nav-icon" size={20} />,
    items: [
      {
        component: CNavGroup,
        name: 'Theme',
        icon: <Palette className="nav-icon" size={20} />,
        items: [
          {
            component: CNavItem,
            name: 'Colors',
            to: '/theme/colors',
            icon: <Palette className="nav-icon" size={20} />,
          },
          {
            component: CNavItem,
            name: 'Typography',
            to: '/theme/typography',
            icon: <Text className="nav-icon" size={20} />,
          },
        ],
      },
      {
        component: CNavGroup,
        name: 'Base',
        to: '/base',
        icon: <Sparkles className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'Accordion', to: '/base/accordion' },
          { component: CNavItem, name: 'Breadcrumb', to: '/base/breadcrumbs' },
          { component: CNavItem, name: 'Carousel', to: '/base/carousels' },
          { component: CNavItem, name: 'Collapse', to: '/base/collapses' },
          { component: CNavItem, name: 'List group', to: '/base/list-groups' },
          { component: CNavItem, name: 'Navs & Tabs', to: '/base/navs' },
          { component: CNavItem, name: 'Pagination', to: '/base/paginations' },
          { component: CNavItem, name: 'Placeholders', to: '/base/placeholders' },
          { component: CNavItem, name: 'Popovers', to: '/base/popovers' },
          { component: CNavItem, name: 'Progress', to: '/base/progress' },
          { component: CNavItem, name: 'Spinners', to: '/base/spinners' },
          { component: CNavItem, name: 'Tabs', to: '/base/tabs' },
          { component: CNavItem, name: 'Tooltips', to: '/base/tooltips' },
        ],
      },
      {
        component: CNavGroup,
        name: 'Buttons',
        to: '/buttons',
        icon: <MousePointer className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'Buttons', to: '/buttons/buttons' },
          { component: CNavItem, name: 'Buttons groups', to: '/buttons/button-groups' },
          { component: CNavItem, name: 'Dropdowns', to: '/buttons/dropdowns' },
        ],
      },
      {
        component: CNavGroup,
        name: 'Forms',
        icon: <FileText className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'Checks & Radios', to: '/forms/checks-radios' },
          { component: CNavItem, name: 'Floating Labels', to: '/forms/floating-labels' },
          { component: CNavItem, name: 'Form Control', to: '/forms/form-control' },
          { component: CNavItem, name: 'Range', to: '/forms/range' },
          { component: CNavItem, name: 'Select', to: '/forms/select' },
          { component: CNavItem, name: 'Layout', to: '/forms/layout' },
          { component: CNavItem, name: 'Validation', to: '/forms/validation' },
        ],
      },
      {
        component: CNavItem,
        name: 'Charts',
        to: '/charts',
        icon: <PieChart className="nav-icon" size={20} />,
      },
      {
        component: CNavGroup,
        name: 'Icons',
        icon: <Sparkles className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'CoreUI Free', to: '/icons/coreui-icons' },
          { component: CNavItem, name: 'CoreUI Flags', to: '/icons/flags' },
          { component: CNavItem, name: 'CoreUI Brands', to: '/icons/brands' },
        ],
      },
      {
        component: CNavGroup,
        name: 'Notifications',
        icon: <Bell className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'Workflow Notifications', to: '/notifications/workflow' },
          { component: CNavItem, name: 'Action Queue', to: '/notifications/tasks' },
        ],
      },
      {
        component: CNavGroup,
        name: 'Pages',
        icon: <FileText className="nav-icon" size={20} />,
        items: [
          { component: CNavItem, name: 'Login', to: '/login' },
          { component: CNavItem, name: 'Register', to: '/register' },
          { component: CNavItem, name: 'Error 404', to: '/404' },
          { component: CNavItem, name: 'Error 500', to: '/500' },
        ],
      },
      {
        component: CNavItem,
        name: 'Docs',
        href: 'https://coreui.io/react/docs/templates/installation/',
        icon: <BookOpen className="nav-icon" size={20} />,
      },
    ],
  },
]

export default _nav
