import React from 'react'
import { CNavItem, CNavTitle } from '@coreui/react'
import {
  BadgeDollarSign,
  Bot,
  BookOpen,
  CalendarDays,
  Clock3,
  ClipboardList,
  ClipboardCheck,
  Download,
  Dumbbell,
  MessageSquareWarning,
  LayoutDashboard,
  LayoutGrid,
  MessageSquareText,
  Settings,
  SlidersHorizontal,
  TriangleAlert,
  UserRound,
  Users,
  UsersRound,
  WalletCards,
  Wrench,
} from 'lucide-react'
import { PWA_INSTALL_ACTION } from 'src/constants/pwa'

const _nav = [
  {
    component: CNavTitle,
    name: 'Home',
  },
  {
    component: CNavItem,
    name: 'Dashboard',
    to: '/dashboard',
    icon: <LayoutDashboard className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Messages',
    to: '/messages',
    icon: <MessageSquareText className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'Reporting',
  },
  {
    component: CNavItem,
    name: 'Inspection',
    to: '/inspection',
    matchPrefix: ['/inspection'],
    'data-testid': 'inspection-nav',
    icon: <ClipboardList className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'ERCO',
    to: '/report/erco',
    matchPrefix: ['/report/erco'],
    icon: <TriangleAlert className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Drill',
    to: '/report/drill',
    matchPrefix: ['/report/drill'],
    icon: <Wrench className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Fitness Test',
    to: '/report/fitness-test',
    matchPrefix: ['/report/fitness-test'],
    icon: <Dumbbell className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'ER Assessment',
    to: '/report/er-assessment',
    matchPrefix: ['/report/er-assessment'],
    icon: <ClipboardCheck className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Reporting Workflow',
    to: '/reporting-settings/inspection',
    matchPrefix: ['/reporting-settings'],
    icon: <SlidersHorizontal className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'People and Operations',
  },
  {
    component: CNavItem,
    name: 'Staff Directory',
    to: '/staff/details',
    icon: <UserRound className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Leave Management',
    to: '/staff/leave-management',
    icon: <CalendarDays className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Overtime Management',
    to: '/staff/overtime-management',
    icon: <Clock3 className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'Payroll',
  },
  {
    component: CNavItem,
    name: 'Payroll Records',
    to: '/staff/salary-claims/salary',
    matchPrefix: [
      '/staff/salary-claims/claims',
      '/staff/salary-claims/salary',
      '/staff/salary-claims/claim',
      '/staff/salary-claims/overtime',
    ],
    icon: <WalletCards className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Payroll Configuration',
    to: '/staff/set-salary/set-salary',
    matchPrefix: ['/staff/set-salary'],
    icon: <BadgeDollarSign className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'Teams and Scheduling',
  },
  {
    component: CNavItem,
    name: 'Team Directory',
    to: '/team/details',
    icon: <UsersRound className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Roster Management',
    to: '/roster/overview',
    icon: <LayoutGrid className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Shift Settings',
    to: '/staff/shift-settings',
    icon: <Settings className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'Administration',
  },
  {
    component: CNavItem,
    name: 'Users',
    to: '/admin/users',
    icon: <Users className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Audit',
    to: '/admin/audit',
    icon: <BookOpen className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Ask AI Reports',
    to: '/admin/ai-helper-reports',
    icon: <Bot className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Feedback Reports',
    to: '/admin/feedback-reports',
    icon: <MessageSquareWarning className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Ask AI Knowledge',
    to: '/admin/ai-helper-knowledge',
    icon: <BookOpen className="nav-icon" size={20} />,
  },
  {
    component: CNavItem,
    name: 'Settings',
    to: '/settings',
    icon: <Settings className="nav-icon" size={20} />,
  },
  {
    component: CNavTitle,
    name: 'App',
  },
  {
    component: CNavItem,
    name: 'Install VMECC',
    action: PWA_INSTALL_ACTION,
    icon: <Download className="nav-icon" size={20} />,
  },
]

export default _nav
